/**:
  ros__parameters:
    hs: 2.5 # significant wave height
    tp: 6.0 # peak period
    gamma: 2.3 # peak factor
    w_min: 0.5 # times the peak frequency
    w_max: 3.0 # times the peak frequency
    N: 100.0 # number of wave components
    dt: 0.1 # time step
